"""Reconciler: regenerate runs/status.json + the CLAUDE.md STATUS block from ground truth.

This is what makes CLAUDE.md self-healing: the load-bearing numbers are stamped from
result.json files, never hand-typed. Stdlib only.

    ./venv/bin/python scripts/update_status.py

Exits non-zero with a DRIFT warning if prose outside the STATUS block contradicts the
generated numbers (a light guardrail; see Self-healing rule 9).
"""
from __future__ import annotations

import copy
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from mario.io import git_rev, utc_now_iso, write_json_atomic  # noqa: E402

RUNS = ROOT / "runs"
CLAUDE = ROOT / "CLAUDE.md"
# Only the original artifact-backed experiment ledger belongs here. Later V4/V5/V6
# documents are research narratives with different gates, not unfinished rows in this
# legacy milestone sequence.
MILESTONES = ["V0", "V1", "V2", "V3"]
BEGIN = "<!-- STATUS:BEGIN (generated by scripts/update_status.py — DO NOT EDIT BY HAND) -->"
END = "<!-- STATUS:END -->"
BASELINE = ROOT / "notes" / "artifacts" / "legacy-status-baseline.json"


def _load_results() -> list[dict]:
    out = []
    for p in sorted(RUNS.glob("*/result.json")):
        try:
            out.append(json.loads(p.read_text()))
        except Exception as e:  # skip malformed, never die
            print(f"WARN: skipping malformed {p}: {e}", file=sys.stderr)
    return out


def _load_evals() -> list[dict]:
    out = []
    for p in sorted(RUNS.glob("*/eval.json")):
        try:
            out.append(json.loads(p.read_text()))
        except Exception as e:
            print(f"WARN: skipping malformed {p}: {e}", file=sys.stderr)
    return out


def _load_bench() -> dict:
    b = {}
    sr = ROOT / "bench" / "step_rate.json"
    sc = ROOT / "bench" / "snapshot_cost.json"
    if sr.exists():
        b["fps"] = json.loads(sr.read_text()).get("fps")
    if sc.exists():
        d = json.loads(sc.read_text())
        b["snapshot_roundtrip_us"] = d.get("roundtrip_us")
        b["nodes_per_s"] = d.get("search_node", {}).get("nodes_per_s")
    return b


def _load_baseline() -> dict:
    try:
        return json.loads(BASELINE.read_text())
    except FileNotFoundError:
        return {}
    except (json.JSONDecodeError, OSError) as exc:
        print(f"WARN: status baseline unreadable: {exc}", file=sys.stderr)
        return {}


def build_status(
        results: list[dict], evals: list[dict] | None = None,
        baseline: dict | None = None) -> dict:
    evals = evals or []
    baseline = _load_baseline() if baseline is None else baseline
    baseline_milestones = baseline.get("milestones", {})
    milestones = {
        m: copy.deepcopy(baseline_milestones.get(m, {"status": "todo"}))
        for m in MILESTONES
    }
    for r in results:
        m = r.get("milestone")
        if m not in milestones:
            continue
        entry = milestones[m]
        if r.get("pass"):
            o = r.get("outcome", {})
            candidate_metrics = {
                k: o.get(k) for k in
                ("beat_level", "framerule_time", "deaths", "completion_frac")
            }
            old_metrics = entry.get("metrics") or {}
            old_time = old_metrics.get("framerule_time")
            new_time = candidate_metrics.get("framerule_time")
            is_better = (
                entry.get("status") != "done"
                or (
                    new_time is not None
                    and (old_time is None or new_time < old_time)
                )
            )
            if is_better:
                entry.update(
                    status="done", best_run=r["run_id"],
                    metrics=candidate_metrics)
        elif entry["status"] == "todo":
            entry["status"] = "in_progress"

    # V1 (dataset) is tracked by data/manifest.json, not a result.json
    man = ROOT / "data" / "manifest.json"
    if man.exists():
        try:
            mlv = json.loads(man.read_text()).get("levels", {})
            n = sum(v.get("n_samples", 0) for v in mlv.values())
            beaten = sum(1 for v in mlv.values() if v.get("has_beaten_trajectory"))
            if beaten > 0:
                old = milestones["V1"].get("metrics") or {}
                if (milestones["V1"].get("status") != "done"
                        or beaten > old.get("levels_beaten", 0)
                        or n > old.get("n_samples", 0)):
                    milestones["V1"].update(
                        status="done", best_run="data/manifest.json",
                        metrics={"n_samples": n, "levels_beaten": beaten})
        except Exception as e:
            print(f"WARN: manifest read failed: {e}", file=sys.stderr)

    # eval.json drives V2+ milestone status (policy results, not search)
    for ev in evals:
        m = ev.get("milestone")
        if m not in milestones:
            continue
        level_1_1 = ev.get("levels", {}).get("1-1")
        if not isinstance(level_1_1, dict):
            continue
        cr = level_1_1.get("completion_rate")
        if cr is None:
            continue
        entry = milestones[m]
        if ev.get("pass"):
            old_cr = (entry.get("metrics") or {}).get("completion_rate")
            if (entry.get("status") != "done"
                    or old_cr is None or cr > old_cr):
                entry.update(status="done", best_run=ev["run_id"],
                             metrics={"completion_rate": cr})
        elif entry["status"] != "done":
            entry.update(status="in_progress", best_run=ev["run_id"],
                         metrics={"completion_rate": cr})

    # current best per level: prefer beaten with lowest framerule_time, else highest completion
    best: dict[str, dict] = copy.deepcopy(baseline.get("current_best", {}))
    for r in results:
        o = r.get("outcome", {})
        # Cross-game key: SMB1 keeps the bare "world-stage" (back-compat); other
        # games are namespaced "game_id:world-stage" so they never collide.
        if not isinstance(r.get("level"), dict):
            continue
        gid = r.get("game_id", "smb1")
        base = f"{r['level']['world']}-{r['level']['stage']}"
        lvl = base if gid == "smb1" else f"{gid}:{base}"
        cand = {"completion_frac": o.get("completion_frac", 0),
                "framerule_time": o.get("framerule_time"),
                "beat": o.get("beat_level", False), "source_run": r["run_id"]}
        cur = best.get(lvl)
        if cur is None:
            best[lvl] = cand
            continue
        if cand["beat"] and (not cur["beat"]
                             or (cand["framerule_time"] or 1e9) < (cur["framerule_time"] or 1e9)):
            best[lvl] = cand
        elif not cur["beat"] and cand["completion_frac"] > cur["completion_frac"]:
            best[lvl] = cand

    # policy evals augment current_best with a learned-policy completion_rate per level.
    # Tolerate foreign eval.json shapes (e.g. the V5 held-out generalist eval has no run_id);
    # the spine must not crash on a new artifact format.
    for ev in evals:
        if "run_id" not in ev or not isinstance(ev.get("levels"), dict):
            continue
        for lvl, lv in ev.get("levels", {}).items():
            if not isinstance(lv, dict):
                continue
            entry = best.setdefault(lvl, {})
            completion = lv.get("completion_rate")
            if completion is None:
                continue
            current = entry.get("policy_completion_rate")
            framerule = lv.get("median_framerule_time")
            current_framerule = entry.get("policy_framerule")
            is_better = current is None or completion > current
            is_faster_tie = (
                completion == current
                and framerule is not None
                and (current_framerule is None or framerule < current_framerule)
            )
            if is_better or is_faster_tie:
                entry["policy_completion_rate"] = completion
                entry["policy_framerule"] = framerule
                entry["policy_run"] = ev["run_id"]

    tests_path = RUNS / "tests.json"
    tests = (
        json.loads(tests_path.read_text())
        if tests_path.exists()
        else copy.deepcopy(baseline.get("tests", {}))
    )

    return {
        "generated_at": utc_now_iso(),
        "generated_by": "update_status.py v3",
        "git_rev": git_rev(),
        "milestones": milestones,
        "current_best": best,
        "bench": _load_bench(),
        "tests": tests,
    }


def render_block(status: dict) -> str:
    lines = [
        "Legacy experiment ledger (artifact-derived; this is not the current roadmap):",
        "",
        "| Milestone | Status | Key metric |",
        "|---|---|---|",
    ]
    labels = {"V0": "V0 beat 1-1 (search)", "V1": "V1 dataset", "V2": "V2 BC clears 1-1",
              "V3": "V3 DAgger"}
    for m in MILESTONES:
        e = status["milestones"][m]
        metric = "—"
        mt = e.get("metrics")
        if mt and "n_samples" in mt:
            metric = f"n_samples={mt.get('n_samples')}, levels_beaten={mt.get('levels_beaten')}"
        elif mt and "completion_rate" in mt:
            completion = mt.get("completion_rate")
            metric = (
                f"completion_rate={completion if completion is not None else 'not recorded'} "
                f"({e.get('best_run','')})"
            )
        elif mt:
            metric = (f"beat={mt.get('beat_level')}, framerule={mt.get('framerule_time')}, "
                      f"deaths={mt.get('deaths')} ({e.get('best_run','')})")
        lines.append(f"| {labels[m]} | {e['status'].upper()} | {metric} |")

    cb = status.get("current_best", {})
    cb_parts = []
    for lvl, v in sorted(cb.items()):
        if v.get("beat"):
            state = f"beat (fr={v.get('framerule_time')})"
        elif "completion_frac" in v:
            state = f"{v['completion_frac']:.0%}"
        else:
            state = ""
        pcr = v.get("policy_completion_rate")
        if pcr is not None:
            state = (state + " " if state else "") + f"net={pcr:.0%}"
        cb_parts.append(f"{lvl}: {state}".strip())
    cb_str = "; ".join(cb_parts) or "none yet"
    b = status.get("bench", {})
    t = status.get("tests", {})
    if t:
        tests_str = (
            f"{t.get('scope', 'recorded scope')}: "
            f"{t.get('passed', '?')} passed / {t.get('failed', '?')} failed"
        )
        if t.get("errors", 0):
            tests_str += f" / {t['errors']} errors"
        if "skipped" in t:
            tests_str += f" / {t['skipped']} skipped"
        if t.get("determinism"):
            tests_str += f"; determinism={t['determinism']}"
    else:
        tests_str = "not recorded"
    footer = (f"\nCurrent best: {cb_str}. "
              f"Tests: {tests_str}. "
              f"Bench: {b.get('fps','?')} fps, snapshot {b.get('snapshot_roundtrip_us','?')}µs, "
              f"{b.get('nodes_per_s','?')} nodes/s. "
              f"_(generated {status['generated_at']}, {status['git_rev']})_")
    return "\n".join(lines) + "\n" + footer


def drift_check(prose: str, status: dict) -> list[str]:
    """Light guardrail: warn if obvious stale metric tokens linger in prose."""
    warnings = []
    # if a milestone is done, prose shouldn't still call it 'in progress'
    for m, e in status["milestones"].items():
        if e["status"] == "done" and re.search(rf"{m}\b.*in progress", prose, re.IGNORECASE):
            warnings.append(f"{m} is DONE but prose still says 'in progress'")
    return warnings


def main() -> int:
    results = _load_results()
    evals = _load_evals()
    status = build_status(results, evals)

    prev = RUNS / "status.json"
    if prev.exists():
        write_json_atomic(RUNS / "status.prev.json", json.loads(prev.read_text()))
    write_json_atomic(prev, status)

    text = CLAUDE.read_text()
    if BEGIN not in text or END not in text:
        print("ERROR: STATUS markers not found in CLAUDE.md", file=sys.stderr)
        return 2
    block = BEGIN + "\n" + render_block(status) + "\n" + END
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)
    CLAUDE.write_text(new)

    prose = new.split(BEGIN)[0] + new.split(END)[-1]
    warns = drift_check(prose, status)
    print("status.json + CLAUDE.md STATUS block updated.")
    for w in warns:
        print("DRIFT:", w, file=sys.stderr)
    return 1 if warns else 0


if __name__ == "__main__":
    raise SystemExit(main())
