"""Reconciler: regenerate runs/status.json + the CLAUDE.md STATUS block from ground truth.

This is what makes CLAUDE.md self-healing: the load-bearing numbers are stamped from
result.json files, never hand-typed. Stdlib only.

    ./venv/bin/python scripts/update_status.py

Exits non-zero with a DRIFT warning if prose outside the STATUS block contradicts the
generated numbers (a light guardrail; see Self-healing rule 9).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from mario.io import git_rev, utc_now_iso, write_json_atomic  # noqa: E402

RUNS = ROOT / "runs"
CLAUDE = ROOT / "CLAUDE.md"
MILESTONES = ["V0", "V1", "V2", "V3", "V4", "V5"]
BEGIN = "<!-- STATUS:BEGIN (generated by scripts/update_status.py — DO NOT EDIT BY HAND) -->"
END = "<!-- STATUS:END -->"


def _load_results() -> list[dict]:
    out = []
    for p in sorted(RUNS.glob("*/result.json")):
        try:
            out.append(json.loads(p.read_text()))
        except Exception as e:  # skip malformed, never die
            print(f"WARN: skipping malformed {p}: {e}", file=sys.stderr)
    return out


def _load_bench() -> dict:
    b = {}
    sr = ROOT / "bench" / "step_rate.json"
    sc = ROOT / "bench" / "snapshot_cost.json"
    if sr.exists():
        b["fps"] = json.loads(sr.read_text()).get("fps")
    if sc.exists():
        d = json.loads(sc.read_text())
        b["snapshot_roundtrip_us"] = d.get("roundtrip_us")
        b["nodes_per_s"] = d.get("search_node", {}).get("nodes_per_s")
    return b


def build_status(results: list[dict]) -> dict:
    milestones = {m: {"status": "todo"} for m in MILESTONES}
    for r in results:
        m = r.get("milestone")
        if m not in milestones:
            continue
        entry = milestones[m]
        if r.get("pass"):
            o = r.get("outcome", {})
            entry.update(status="done", best_run=r["run_id"],
                         metrics={k: o.get(k) for k in
                                  ("beat_level", "framerule_time", "deaths", "completion_frac")})
        elif entry["status"] == "todo":
            entry["status"] = "in_progress"

    # current best per level: prefer beaten with lowest framerule_time, else highest completion
    best: dict[str, dict] = {}
    for r in results:
        o = r.get("outcome", {})
        lvl = f"{r['level']['world']}-{r['level']['stage']}"
        cand = {"completion_frac": o.get("completion_frac", 0),
                "framerule_time": o.get("framerule_time"),
                "beat": o.get("beat_level", False), "source_run": r["run_id"]}
        cur = best.get(lvl)
        if cur is None:
            best[lvl] = cand
            continue
        if cand["beat"] and (not cur["beat"]
                             or (cand["framerule_time"] or 1e9) < (cur["framerule_time"] or 1e9)):
            best[lvl] = cand
        elif not cur["beat"] and cand["completion_frac"] > cur["completion_frac"]:
            best[lvl] = cand

    tests_path = RUNS / "tests.json"
    tests = json.loads(tests_path.read_text()) if tests_path.exists() else {}

    return {
        "generated_at": utc_now_iso(),
        "generated_by": "update_status.py v1",
        "git_rev": git_rev(),
        "milestones": milestones,
        "current_best": best,
        "bench": _load_bench(),
        "tests": tests,
    }


def render_block(status: dict) -> str:
    lines = ["| Milestone | Status | Key metric |", "|---|---|---|"]
    labels = {"V0": "V0 beat 1-1 (search)", "V1": "V1 dataset", "V2": "V2 BC clears 1-1",
              "V3": "V3 DAgger", "V4": "V4 multi-world", "V5": "V5 value+speed"}
    for m in MILESTONES:
        e = status["milestones"][m]
        metric = "—"
        if e.get("metrics"):
            mt = e["metrics"]
            metric = (f"beat={mt.get('beat_level')}, framerule={mt.get('framerule_time')}, "
                      f"deaths={mt.get('deaths')} ({e.get('best_run','')})")
        lines.append(f"| {labels[m]} | {e['status'].upper()} | {metric} |")

    cb = status.get("current_best", {})
    cb_parts = []
    for lvl, v in sorted(cb.items()):
        state = "beat" if v["beat"] else f"{v['completion_frac']:.0%}"
        cb_parts.append(f"{lvl}: {state} (fr={v['framerule_time']})")
    cb_str = "; ".join(cb_parts) or "none yet"
    b = status.get("bench", {})
    t = status.get("tests", {})
    tests_str = (f"{t.get('passed','?')} passed / {t.get('failed','?')} failed"
                 if t else "not recorded")
    footer = (f"\nCurrent best: {cb_str}. "
              f"Tests: {tests_str}. "
              f"Bench: {b.get('fps','?')} fps, snapshot {b.get('snapshot_roundtrip_us','?')}µs, "
              f"{b.get('nodes_per_s','?')} nodes/s. "
              f"_(generated {status['generated_at']}, {status['git_rev']})_")
    return "\n".join(lines) + "\n" + footer


def drift_check(prose: str, status: dict) -> list[str]:
    """Light guardrail: warn if obvious stale metric tokens linger in prose."""
    warnings = []
    # if a milestone is done, prose shouldn't still call it 'in progress'
    for m, e in status["milestones"].items():
        if e["status"] == "done" and re.search(rf"{m}\b.*in progress", prose, re.IGNORECASE):
            warnings.append(f"{m} is DONE but prose still says 'in progress'")
    return warnings


def main() -> int:
    results = _load_results()
    status = build_status(results)

    prev = RUNS / "status.json"
    if prev.exists():
        write_json_atomic(RUNS / "status.prev.json", json.loads(prev.read_text()))
    write_json_atomic(prev, status)

    text = CLAUDE.read_text()
    if BEGIN not in text or END not in text:
        print("ERROR: STATUS markers not found in CLAUDE.md", file=sys.stderr)
        return 2
    block = BEGIN + "\n" + render_block(status) + "\n" + END
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)
    CLAUDE.write_text(new)

    prose = new.split(BEGIN)[0] + new.split(END)[-1]
    warns = drift_check(prose, status)
    print("status.json + CLAUDE.md STATUS block updated.")
    for w in warns:
        print("DRIFT:", w, file=sys.stderr)
    return 1 if warns else 0


if __name__ == "__main__":
    raise SystemExit(main())
